### ISSUE TITLE
Just hangs after program exit on windows

### ISSUE THREAD

**Issue by fabianbergmark** [flamegraph-rs/flamegraph#125] opened 2021-02-22 12:03 UTC
cargo flamegraph --bin world                                                      
Compiling world v0.1.0 (C:\src\world)                                             
Finished release [optimized + debuginfo] target(s) in 57.01s                 
dtrace: description 'profile-997 ' matched 1 probe                              
dtrace: pid 2040 has exited

It then hangs without producing any .svg image, there is however a cargo-flamegraph.stacks file

**Comment by djc** [comment] 2021-02-22 12:08
Oops! Unfortunately I don't have access to Windows infrastructure, so I probably cannot contribute much here. Can you add some debug statements in the source code to bisect what part is hanging?

**Comment by Inky-developer** [comment] 2021-02-22 15:50
I got the same problem on windows. Also, this seems to be a duplicate of #105

**Comment by Inky-developer** [comment] 2021-02-22 18:18
I have done some inevstigations, and the programs always hangs at this point: https://github.com/flamegraph-rs/flamegraph/blob/5f7a918793ef959a3e29d1211412a9dc027fe232/src/lib.rs#L264-L265
This line runs dtrace. I get the same freeze when running the dtrace command manually. Unfortunately I don't know how dtrace works so I cannot investigate really further.
This is the exact dtrace command that is run: ` "dtrace" "-x" "ustackframes=100" "-n" "profile-997 /pid == $target/ { @[ustack(100)] = count(); }" "-o" "cargo-flamegraph.stacks" "-c" "<my_project_dir>"`

**Comment by nico-abram** [comment] 2021-03-10 17:44
This issue seems to be a duplicate of https://github.com/flamegraph-rs/flamegraph/issues/105 and that is duplicate of https://github.com/flamegraph-rs/flamegraph/issues/3

Also, this issue seems to be in windows dtrace, not in flamegraph. See [this issue](https://github.com/microsoft/DTrace-on-Windows/issues/4) in the dtrace repo
I sent a pull request that should fix this specific issue, it was merged but a version has not been released with it yet

**Comment by djc** [comment] 2021-03-10 21:21
Let's close this in favor of #3 for now. @nico-abram thanks for doing the work reporting this upstream?

**Closed by djc** 2021-03-10 21:21 UTC
