### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by jamesmunns** [flamegraph-rs/flamegraph#3] opened 2019-03-11 20:14 UTC
Windows now experimentally [supports DTrace](https://techcommunity.microsoft.com/t5/Windows-Kernel-Internals/DTrace-on-Windows/ba-p/362902), which could allow for possible profiling with cargo-flamegraph

**Comment by spacejam** [comment] 2019-03-12 11:27
it's possible that this already works then, because dtrace is selected as the profiler for anything that isn't linux

**Comment by TheGoddessInari** [comment] 2019-03-18 12:54
It's worth noting that the `signal-hook` dependency and usage is currently preventing building on Windows.

**Comment by jonhoo** [comment] 2019-03-18 14:01
Sounds like a Windows CI target may be a good idea.

**Comment by vadixidav** [comment] 2019-04-20 20:47
So it would seem that signal-hook doesn't have any issues open for adding Windows support, and I am not familiar with the issue, but I imagine it might not be possible. Is there some other way flamegraph can be implemented on Windows without `signal-hook`?

**Comment by TheGoddessInari** [comment] 2019-04-20 20:52
Yes, there are other SIGINT handler crates that support more than one platform.
If you don't need to handle SIGINT well during I/O, there's [ctrlc](https://github.com/Detegr/rust-ctrlc).
If you do, using a signal handler via [tokio](https://tokio.rs/) might be necessary.

**Comment by jonas-schievink** [comment] 2019-12-03 11:12
Flamegraph now builds on Windows, and a Windows build is done in CI too. It would be great if someone could test this.

**Comment by TheGoddessInari** [comment] 2019-12-03 11:55
```
C:\Projects\flamegraph>cargo flamegraph --bin flamegraph
    Finished release [optimized] target(s) in 0.12s

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true

thread 'main' panicked at 'could not spawn dtrace: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1189:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jonas-schievink** [comment] 2019-12-03 12:38
Make sure that `dtrace` is installed and in `PATH`. You also need to enable the insider builds I believe. You can follow the instructions here: https://techcommunity.microsoft.com/t5/Windows-Kernel-Internals/DTrace-on-Windows/ba-p/362902

**Comment by TheGoddessInari** [comment] 2019-12-04 21:55
I was able to install dtrace on a Windows Insider build, it then proceeds as far as this: 
```
C:\Projects\flamegraph>cargo flamegraph --bin flamegraph
   Compiling flamegraph v0.1.13 (C:\Projects\flamegraph)
    Finished release [optimized + debuginfo] target(s) in 3.19s

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true

dtrace: invalid probe specifier profile-997 /
```

**Comment by TheGoddessInari** [comment] 2019-12-04 21:56
Adding the specified lines to Cargo.toml did not help.

**Comment by jonas-schievink** [comment] 2019-12-05 13:04
@TheGoddessInari Thanks for testing this! Flamegraph seems to work fine on macOS, so this looks like an issue with the Windows support for DTrace, or maybe a difference in how DTrace scripts are parsed.

**Comment by Knight-Ops** [comment] 2019-12-06 03:57
Using the same testing as @TheGoddessInari 

```
dtrace: failed to initialize dtrace: Invalid argument
failed to sample program
```

This is both for `flamegraph` and `cargo flamegraph`.

I haven't messed with dtrace before, but I can't seem to get Windows dtrace to accept arguments that it says it accepts.

```
PS F:\git\flamegraph> dtrace.exe -x ustackframes=100
dtrace: failed to initialize dtrace: Invalid argument
```

I tried going through the arguments in `lib.rs` without much luck one at a time and all together. So either DTrace support is very light in terms of accepted arguments to the binary, I am doing it wrong, or the DTrace script is different as you said.

**Comment by jonas-schievink** [comment] 2019-12-06 10:26
Aw, that's unfortunate. I guess that means no Windows support for now. I would merge a PR that fixes this, or that adds an alternative profiling backend for Windows though (does Visual Studio ship some standard CLI tool for this?).

**Comment by bitemyapp** [comment] 2020-02-22 21:12
I'm getting this same error on macOS: https://github.com/flamegraph-rs/flamegraph/issues/3#issuecomment-561856986

```
dtrace: system integrity protection is on, some features will not be available

dtrace: invalid probe specifier profile-997 /pid == $target/ { @[ustack(100)] = count(); }: extraneous argument 'rust' ($1 is not referenced)
failed to sample program
```

Debug is enabled for the release profile.

**Comment by Kixiron** [comment] 2020-03-19 17:38
If dtrace falls through, [xperf](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/xperf-command-line-reference) could be a valid alternative, as used in [UIforETW](https://github.com/google/UIforETW). A upside of using xperf is that it also allows immediate implementation, as it works on any windows build, not just insiders

**Comment by TheGoddessInari** [comment] 2020-03-31 00:21
DTrace on Windows got updated (new MSI package and driver as of January), so now the problem is that flamegraph never exits or produces output. The process getting traced exits, dtrace does nothing special by default upon process exit, and if you ctrl-C, it merely kills flamegraph (because no signal handler on Windows).

**Comment by jasonwilliams** [comment] 2020-04-01 10:28
> DTrace on Windows got updated (new MSI package and driver as of January), so now the problem is that flamegraph never exits or produces output. The process getting traced exits, dtrace does nothing special by default upon process exit, and if you ctrl-C, it merely kills flamegraph (because no signal handler on Windows).

Is it still only on insiders build?
Also, thanks for looking into this

**Comment by jarrett** [comment] 2020-04-18 18:50
I am seeing the same behavior as @TheGoddessInari. With both `flamegraph [path to executable` and `cargo flamegraph`, the process being traced terminates, but dtrace never terminates on its own and doesn't write the SVG file. CTRL-C kill dtrace before the SVG gets written.

@jasonwilliams As of today, it still requires an Insider build.

**Comment by nico-abram** [comment] 2021-02-18 00:24
I tried this today, installed latest dtrace from https://www.microsoft.com/en-us/download/details.aspx?id=100441 (Published 1/23/2020) following the instructions at https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace and  got the same behaviour. Eventually I got this output:

```
dtrace: pid 3704 has exited
dtrace: processing aborted: Abort due to systemic unresponsiveness
failed to sample program
```

I looked at the processes in process hacker while it was stuck and the dtrace process was still going, so it's probably not terminating for some reason

**Comment by nico-abram** [comment] 2021-02-18 00:45
Just running dtrace on windows with the following command (I patched cargo-flamegraph to dbg!(&command) to get it) reproduces the issue

```
dtrace "-x" "ustackframes=100" "-n" 'profile-997 /pid == $target/ { @[ustack(100)] = count(); }' "-o" "cargo-flamegraph.stacks" "-c" "D:\\dev\\playground\\target\\release\\playground"
```

I'm gonna try reporting this with their [feedback tool](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace#providing-feedback-on-windows-dtrace)

**Comment by Ciantic** [comment] 2021-02-27 22:17
Stuffing to their feedback tool has never worked for me, but glad you tried @nico-abram.

The `dtrace.exe` has [GitHubd repository](https://github.com/microsoft/DTrace-on-Windows) but it doesn't allow filing issues, I guess they think their implementation is flawless. 

However it probably isn't and tried to ask in [Windows-Rs repository](https://github.com/microsoft/windows-rs/discussions/571) if they are willing to open up an issue section in `dtrace.exe` repo so we could file the issue there.

**Comment by nico-abram** [comment] 2021-02-28 03:03
I considered trying to compile and debug it myself since it's apparently available, but both branches in their repository were last updated in 2019, while the last version of dtrace published on their page is from 1/23/2020, meaning it is likely not up to date

**Comment by rylev** [comment] 2021-03-01 12:31
As noted in https://github.com/microsoft/windows-rs/discussions/571#discussioncomment-417767, I'm going to try to see what's up with the dtrace repo and if we can get someone to look into this.

**Comment by rylev** [comment] 2021-03-01 21:42
Issues are now open on the repo: https://github.com/microsoft/DTrace-on-Windows/issues. Let’s add an issue there.

**Comment by nico-abram** [comment] 2021-03-02 20:39
With the dtrace patch I mentioned in [this comment](https://github.com/microsoft/DTrace-on-Windows/issues/4#issuecomment-789192235)

I was able to generate [this svg](https://hatebin.com/zcnsqbjlkv) (It's text because I couldn't find a service to upload it) using cargo flamegraph
![imagen](https://user-images.githubusercontent.com/24706838/109711930-2b733b80-7b7e-11eb-8383-97c748960f2a.png)

**Comment by Ciantic** [comment] 2021-03-06 22:24
🎉 @nico-abram's patch to dtrace.exe was merged ( https://github.com/microsoft/DTrace-on-Windows/pull/6 ) 

Hopefully they will release a new version soon 🤞

**Comment by KnoxZZ** [comment] 2021-12-15 13:28
I guess Microsoft hasn't released a new version since @nico-abram patch since getting flamegraph to work still required compiling the Dtrace-on-Windows project from the sources. 

The current version installed by the installer is 1.13.1.

**Closed** 2022-05-11 13:06 UTC

**Comment by kaleidawave** [comment] 2024-09-08 07:28
I have got the `dtrace` working under windows and `cargo-flamegraph` is generating `flamegraph.svg`.

However running on a project I am working on doesn't seem to generate useful results with mostly `ntdll` calls and nothing relevant to functions in the project?

![image](https://github.com/user-attachments/assets/b773873a-5dca-459c-a912-d9b2f30c0d4a)

Are there any good examples of Rust to test a flamegraph on? Or is there maybe a problem with my `dtrace` setup?

**Comment by djc** [comment] 2024-09-09 08:05
I don't have much experience with flamegraph on Windows, but I'd suggest trying the blondie backend instead of the dtrace stuff, which IIUC builds on Windows-native profiling infrastructure.
