### ISSUE TITLE
DTrace implementation not working

### ISSUE THREAD

**Issue by ccgauche** [flamegraph-rs/flamegraph#105] opened 2020-12-01 17:49 UTC
I'm currently probing perfs of a simple rust project. I've so wanted to try the dtrace version of flame graph.
But after dtrace execution flame graph seems to be stuck. 
This looks like an issue with DTrace or something like that.

![image](https://user-images.githubusercontent.com/16625987/100776938-70fc5d00-3405-11eb-9f41-f479f1a1b3da.png)
All `not in method` messages are from my program.

If this can help, flame graph and DTrace are not using CPU at all.
DTrace is opened in the task manager and when closed we get:

![image](https://user-images.githubusercontent.com/16625987/100777196-c59fd800-3405-11eb-8326-4f5cc6e5f9a2.png)

**Comment by agersant** [comment] 2020-12-06 09:34
Same results here (I just tried `cargo flamegraph` for the first time). In case that matters, I got my `dtrace` executable from [here](https://www.microsoft.com/en-us/download/details.aspx?id=100441).

**Comment by nico-abram** [comment] 2021-03-10 17:44
This issue seems to be a duplicate of https://github.com/flamegraph-rs/flamegraph/issues/3

Also, this issue seems to be in windows dtrace, not in flamegraph. See [this issue](https://github.com/microsoft/DTrace-on-Windows/issues/4) in the dtrace repo
I sent a pull request that should fix this specific issue, it was merged but a version has not been released with it yet

**Comment by djc** [comment] 2021-03-10 21:21
Let's close this in favor of #3 for now.

**Closed by djc** 2021-03-10 21:21 UTC
